steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "jarvis-bot"
      - "--image"
      - "gcr.io/$PROJECT_ID/jarvis-bot"
      - "--region"
      - "asia-east2"
      - "--platform"
      - "managed"
      - "--port"
      - "8080"
      - "--allow-unauthenticated"